### ISSUE TITLE
Day-1 q1: Product of Array Except Self

### ISSUE THREAD

**Issue by prachisinhaa** [SnowScriptWinterOfCode/LeetCode_Q#1]
Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].

The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer.

You must write an algorithm that runs in O(n) time and without using the division operation.

Example 1:
Input: nums = [1,2,3,4]
Output: [24,12,8,6]

Example 2
Input: nums = [-1,1,0,-3,3]
Output: [0,0,9,0,0]

**Comment by aarushisingh2004** [comment]
please assign this to me

**Comment by aarushisingh2004** [comment]
di can u plz clarify once in which folder it needs to be committed

**Comment by aarushisingh2004** [comment]
I have sent a pull request , plz check
