### ISSUE TITLE
Day-3 q1: Spiral Matrix

### ISSUE THREAD

**Issue by SonaVarshney** [SnowScriptWinterOfCode/LeetCode_Q#11]
Given an m x n matrix, return all elements of the matrix in spiral order.

![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/99477385/25fd37d5-b2f2-44ad-9749-5ff20a4650ba)
Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [1,2,3,6,9,8,7,4,5]

![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/99477385/b0c3dd74-b348-4d80-bc35-68bd5649ecc4)
Input: matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
Output: [1,2,3,4,8,12,11,10,9,5,6,7]
 
Constraints:

1) m == matrix.length
2) n == matrix[i].length
3) 1 <= m, n <= 10
4) -100 <= matrix[i][j] <= 100

**Comment by Ipshita-Tandon** [comment]
I would love to work on this issue, please assign it to me!

**Comment by SonaVarshney** [comment]
@bh-g please add this as the solution. Thanks!
https://github.com/SnowScriptWinterOfCode/LeetCode_Q/pull/142#issue-2061395171  #142

**Comment by Akansha77** [comment]
Please assign this issue to me.
