### ISSUE TITLE
2513. Minimize the Maximum of Two Arrays

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [SnowScriptWinterOfCode/LeetCode_Q#115]
Hi, I want to add this question to this repository along with its solution. Kindly assign this to me @bh-g  [2513. Minimize the Maximum of Two Arrays](https://leetcode.com/problems/minimize-the-maximum-of-two-arrays/)

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me
