### ISSUE TITLE
229. Majority Element II

### ISSUE THREAD

**Issue by aishwarya-chandra** [SnowScriptWinterOfCode/LeetCode_Q#120]
I want to contribute to the repo by adding this question as well as its solution.
Kindly assign me this. @bh-g  @kratika-Jangid 
https://leetcode.com/problems/majority-element-ii/description/

**Comment by Akansha77** [comment]
Please assign this to me.

**Comment by Akansha77** [comment]
where I upload the solution for this there is no file in the repo named majority element 2

**Comment by Akansha77** [comment]
@bh-g @kratika-Jangid 
are you able to see my file?
