### ISSUE TITLE
Single Element in a Sorted Array

### ISSUE THREAD

**Issue by Karnankita04** [SnowScriptWinterOfCode/LeetCode_Q#13]
You are given a sorted array consisting of only integers where every element appears exactly twice, except for one element which appears exactly once.

Return the single element that appears only once.

Your solution must run in O(log n) time and O(1) space.

Example 1:
Input: nums = [1,1,2,3,3,4,4,8,8]
Output: 2

Example 2:
Input: nums = [3,3,7,7,10,11,11]
Output: 10

Constraints:
1 <= nums.length <= 105
0 <= nums[i] <= 105

**Comment by Karnankita04** [comment]
Can I start working on this issue??

**Comment by bh-g** [comment]
@Karnankita04 Add this question in the **Others** folder so that everyone can post solutions for it, refer template inside **Others** for the same.

**Comment by bh-g** [comment]
Question added in repo.
