### ISSUE TITLE
Add Binary

### ISSUE THREAD

**Issue by Shubh-Krishna** [SnowScriptWinterOfCode/LeetCode_Q#139]
# Add Binary
Given two binary strings a and b, return their sum as a binary string.

 
Example 1:

Input: a = "11", b = "1"
Output: "100"
Example 2:

Input: a = "1010", b = "1011"
Output: "10101"

**Comment by Shubh-Krishna** [comment]
please assign this issue to me :) @bh-g

**Comment by Ipshita-Tandon** [comment]
Please assign this issue to me
