### ISSUE TITLE
Day-5 Q1: Search a 2D matrix

### ISSUE THREAD

**Issue by prachisinhaa** [SnowScriptWinterOfCode/LeetCode_Q#146]
You are given an m x n integer matrix with the following two properties:

Each row is sorted in non-decreasing order.
The first integer of each row is greater than the last integer of the previous row.
Given an integer target, return true if target is in matrix or false otherwise.

You must write a solution in O(log(m * n)) time complexity.

 

Example 1:
Input: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3
Output: true

Example 2:
Input: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 13
Output: false

**Comment by Akansha77** [comment]
Please assign this question to me.

**Comment by Shubh-Krishna** [comment]
please assign this question to me :) @bh-g

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by Karnankita04** [comment]
Please assign this issue to me :) I would like to do it with new approach..

**Comment by Karnankita04** [comment]
@bh-g please review the PR I just made..
