### ISSUE TITLE
Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by Ipshita-Tandon** [SnowScriptWinterOfCode/LeetCode_Q#15]
Given a binary tree, find the lowest common ancestor (LCA) of two given nodes in the tree.

According to the [definition of LCA on Wikipedia](https://en.wikipedia.org/wiki/Lowest_common_ancestor): “The lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants (where we allow a node to be a descendant of itself).”

Example 1:
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/120296010/5ba24647-b323-4d12-a97a-2cb604ab9c22)

Input: root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1
Output: 3
Explanation: The LCA of nodes 5 and 1 is 3.

Example 2:
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/120296010/4ccadc4f-acf3-48f5-a5d4-8fbf931806b5)

Input: root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 4
Output: 5
Explanation: The LCA of nodes 5 and 4 is 5, since a node can be a descendant of itself according to the LCA definition.

Example 3:
Input: root = [1,2], p = 1, q = 2
Output: 1
 

Constraints:

1. The number of nodes in the tree is in the range [2, 105].
2. -109 <= Node.val <= 109
3. All Node.val are unique.
4. p != q
5. p and q will exist in the tree.

**Comment by Ipshita-Tandon** [comment]
Can I please start working on this issue?

**Comment by bh-g** [comment]
@Ipshita-Tandon Add this question in the Others folder so that everyone can post solutions for it, refer to the template inside Others for the same.
Do the same for the other issues you've created as well.

**Comment by Deepika8383** [comment]
can you please assign it to me

**Comment by Ipshita-Tandon** [comment]
> @Ipshita-Tandon Add this question in the Others folder so that everyone can post solutions for it, refer to the template inside Others for the same. Do the same for the other issues you've created as well.

Sure di, on it!
