### ISSUE TITLE
Check if the array is Sorted and Rotated

### ISSUE THREAD

**Issue by Karnankita04** [SnowScriptWinterOfCode/LeetCode_Q#152]
Given an array nums, return true if the array was originally sorted in non-decreasing order, then rotated some number of positions (including zero). Otherwise, return false.

There may be duplicates in the original array.

Note: An array A rotated by x positions results in an array B of the same length such that A[i] == B[(i+x) % A.length], where % is the modulo operation. 

Example 1:

Input: nums = [3,4,5,1,2]
Output: true
Explanation: [1,2,3,4,5] is the original sorted array.
You can rotate the array by x = 3 positions to begin on the the element of value 3: [3,4,5,1,2].

Example 2:

Input: nums = [2,1,3,4]
Output: false
Explanation: There is no sorted array once rotated that can make nums.

Example 3:

Input: nums = [1,2,3]
Output: true
Explanation: [1,2,3] is the original sorted array.
You can rotate the array by x = 0 positions (i.e. no rotation) to make nums.

Constraints:

1 <= nums.length <= 100
1 <= nums[i] <= 100

Link: https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/description/

**Comment by Karnankita04** [comment]
Please assign this issue to me :)

**Comment by Akansha77** [comment]
Please assign this to me @bh-g

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by Karnankita04** [comment]
@bh-g  would you please review the PR I made just now :)

**Comment by priyagupta20044** [comment]
Please assign this issue to me, I would like to add my solution

**Comment by namita0210** [comment]
@bh-g  - I want to solve this question using Java
Please assign this issue to me.
