### ISSUE TITLE
Asteroid Collision

### ISSUE THREAD

**Issue by Ipshita-Tandon** [SnowScriptWinterOfCode/LeetCode_Q#16]
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/120296010/f51d8ead-086c-47b0-84f5-094557d7c402)

We are given an array asteroids of integers representing asteroids in a row.

For each asteroid, the absolute value represents its size, and the sign represents its direction (positive meaning right, negative meaning left). Each asteroid moves at the same speed.

Find out the state of the asteroids after all collisions. If two asteroids meet, the smaller one will explode. If both are the same size, both will explode. Two asteroids moving in the same direction will never meet.

Example 1:
Input: asteroids = [5,10,-5]
Output: [5,10]
Explanation: The 10 and -5 collide resulting in 10. The 5 and 10 never collide.

Example 2:
Input: asteroids = [8,-8]
Output: []
Explanation: The 8 and -8 collide exploding each other.

Example 3:
Input: asteroids = [10,2,-5]
Output: [10]
Explanation: The 2 and -5 collide resulting in -5. The 10 and -5 collide resulting in 10.

Constraints:

1. 2 <= asteroids.length <= 104
2. -1000 <= asteroids[i] <= 1000
3. asteroids[i] != 0

**Comment by Ipshita-Tandon** [comment]
Can I please start working on this issue?

**Comment by bh-g** [comment]
Add this question in Others/ Asteroid Collision/ question.md file.

**Comment by Karnankita04** [comment]
Please assign this issue to me :)
