### ISSUE TITLE
Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by namita0210** [SnowScriptWinterOfCode/LeetCode_Q#17]
**Problem Statement**
You are given an array of characters letters that is sorted in non-decreasing order, and a character target. There are at least two different characters in letters.

Return the smallest character in letters that is lexicographically greater than target. If such a character does not exist, return the first character in letters.

[leetcode question link](https://leetcode.com/problems/find-smallest-letter-greater-than-target/?envType=study-plan-v2&envId=binary-search)

**Comment by namita0210** [comment]
@Nitya-Pasrija Can you please assign this issue to me.

**Comment by bh-g** [comment]
@namita0210 Add this question in the Others folder so that everyone can post solutions for it, refer to the template inside Others for the same.

**Comment by namita0210** [comment]
> @namita0210 Add this question in the Others folder so that everyone can post solutions for it, refer to the template inside Others for the same.

Okay - will do :)

**Comment by bh-g** [comment]
Added to repo!
