### ISSUE TITLE
Day 5: Rotate Image

### ISSUE THREAD

**Issue by Mansi8874** [SnowScriptWinterOfCode/LeetCode_Q#175]
You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

Example 1:
Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [[7,4,1],[8,5,2],[9,6,3]]
<img width="395" alt="Screenshot 2024-01-01 at 9 16 48 PM" src="https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/101468475/bfe75b11-c66d-4966-850e-21189db84613">

Example 2:
Input: matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
Output: [[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]
 <img width="398" alt="Screenshot 2024-01-01 at 9 16 53 PM" src="https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/101468475/e7caff48-ea78-4dd9-8eac-a0a1d5fccbc5">

Constraints:
n == matrix.length == matrix[i].length
1 <= n <= 20
-1000 <= matrix[i][j] <= 1000

**Comment by priyagupta20044** [comment]
Please assign this to me, I would like to add the solution for it

**Comment by bh-g** [comment]
Hey Mansi! This ques is already present in Other/
