### ISSUE TITLE
N-Queens

### ISSUE THREAD

**Issue by Ipshita-Tandon** [SnowScriptWinterOfCode/LeetCode_Q#18]
The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.

Given an integer n, return all distinct solutions to the n-queens puzzle. You may return the answer in any order.

Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space, respectively.

 

Example 1:
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/120296010/31a1b503-0572-45dc-87da-e7db311ac4eb)

Input: n = 4
Output: [[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]
Explanation: There exist two distinct solutions to the 4-queens puzzle as shown above

Example 2:

Input: n = 1
Output: [["Q"]]
 

Constraints:
1 <= n <= 9

**Comment by Ipshita-Tandon** [comment]
Please assign this issue to me :)

**Comment by bh-g** [comment]
Hey Ishita, when creating a PR, it would be helpful to refer the specific issue you're working on. This ensures better context and understanding!

**Comment by Ipshita-Tandon** [comment]
> Hey Ishita, when creating a PR, it would be helpful to refer the specific issue you're working on. This ensures better context and understanding!

Sorry for the confusion di, will do that from now, thank you for the tip!

**Comment by Ipshita-Tandon** [comment]
@bh-g didi I had a few doubts. where can we post answers for the daily questions?
Also di if someone has already posted a solution for a question present in 'others', can I still add my answer there?

**Comment by bh-g** [comment]
Hey @Ipshita-Tandon 
The instructions to add solutions for daily questions are there in the file itself: you can refer this Day-2/q2: Merge Sorted Arrays/Anomasingh--C.md
Yes, you can if you have a different approach or you have solved it in a different language!

**Comment by Ipshita-Tandon** [comment]
> Hey @Ipshita-Tandon The instructions to add solutions for daily questions are there in the file itself: you can refer this Day-2/q2: Merge Sorted Arrays/Anomasingh--C.md Yes, you can if you have a different approach or you have solved it in a different language!

Okay di, thank you so much!
