### ISSUE TITLE
Word Search

### ISSUE THREAD

**Issue by Ipshita-Tandon** [SnowScriptWinterOfCode/LeetCode_Q#19]
Given an m x n grid of characters board and a string word, return true if word exists in the grid.

The word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighbouring. The same letter cell may not be used more than once.

 
Example 1:
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/120296010/cf31aad3-eb54-4a1e-aa1c-1bce8cf27c5b)

Input: board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCCED"
Output: true

Example 2:
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/120296010/d4bf1a2c-2251-4409-b160-6e2390ca044e)

Input: board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "SEE"
Output: true

Example 3:
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/120296010/15db2221-db87-4148-b2e4-4eacb1e30c79)

Input: board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCB"
Output: false
 

Constraints:

1. m == board.length
2. n = board[i].length
3. 1 <= m, n <= 6
4. 1 <= word.length <= 15
5. board and word consists of only lowercase and uppercase English letters.

**Comment by Ipshita-Tandon** [comment]
Please assign this issue to me :)

**Comment by Shubh-Krishna** [comment]
Please assign this issue to me .

**Comment by bh-g** [comment]
@Ipshita-Tandon @Shubh-Krishna 
Make a new file Others/ Word Search/ question.md and add this question there.
