### ISSUE TITLE
Day 5-q2 Group Anagrams

### ISSUE THREAD

**Issue by div910** [SnowScriptWinterOfCode/LeetCode_Q#197]
[Group Anagrams](https://leetcode.com/problems/group-anagrams/)

Given an array of strings strs, group the anagrams together. You can return the answer in any order.

An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.

Example 1:

Input: strs = ["eat","tea","tan","ate","nat","bat"]
Output: [["bat"],["nat","tan"],["ate","eat","tea"]]

Example 2:

Input: strs = [""]
Output: [[""]]

Example 3:

Input: strs = ["a"]
Output: [["a"]]

**Comment by Shubh-Krishna** [comment]
please add this question to me :) @bh-g

**Comment by shahin-04** [comment]
Hey, I'd like to contribute. Could you please assign this task to me?
