### ISSUE TITLE
Day-4 q2: Minimum Number of Flips

### ISSUE THREAD

**Issue by DiyaSingla** [SnowScriptWinterOfCode/LeetCode_Q#20]
Given a binary string, that is it contains only 0s and 1s. We need to make this string a sequence of alternate characters by flipping some of the bits, our goal is to minimize the number of bits to be flipped.

Example 1:

Input:
S = "001"
Output: 1
Explanation: We can flip the 0th bit to 1 to have 101.

Example 2:

Input:
S = "0001010111" 
Output: 2
Explanation: We can flip the 1st and 8th bit bit to have "0101010101"

**Comment by Shubh-Krishna** [comment]
I would love to work in this issue .Please assign it to me :)

**Comment by Shubh-Krishna** [comment]
please assign this question to me :)

**Comment by shubhimaurya** [comment]
@bh-g  i would really love to work on this, please assign this to me, thankyou

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me @bh-g
