### ISSUE TITLE
118. Pascal's Triangle

### ISSUE THREAD

**Issue by aarushisingh2004** [SnowScriptWinterOfCode/LeetCode_Q#209]
Given an integer numRows, return the first numRows of Pascal's triangle.

In Pascal's triangle, each number is the sum of the two numbers directly above it as shown:

 

Example 1:

Input: numRows = 5
Output: [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]
Example 2:

Input: numRows = 1
Output: [[1]]
 

Constraints:

1 <= numRows <= 30

**Comment by Gurn-k** [comment]
Please assign this issue to me

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by Shubh-Krishna** [comment]
please assign this question to me :)

**Comment by shahin-04** [comment]
@bh-g Hey, I'd like to contribute. Could you please assign this task to me?

**Comment by priyagupta20044** [comment]
please assign this question to me
 @bh-g
