### ISSUE TITLE
152. Maximum Product Subarray

### ISSUE THREAD

**Issue by aarushisingh2004** [SnowScriptWinterOfCode/LeetCode_Q#210]
Given an integer array nums, find a 
subarray
 that has the largest product, and return the product.

The test cases are generated so that the answer will fit in a 32-bit integer.

 

Example 1:

Input: nums = [2,3,-2,4]
Output: 6
Explanation: [2,3] has the largest product 6.
Example 2:

Input: nums = [-2,0,-1]
Output: 0
Explanation: The result cannot be 2, because [-2,-1] is not a subarray.

**Comment by Shubhra-Narang** [comment]
@bh-g Please assign this issue to me

**Comment by Shubh-Krishna** [comment]
please assign this to me :) @bh-g

**Comment by Akansha77** [comment]
Please assign this issue to me @bh-g .
