### ISSUE TITLE
Day 6 q1: Convert an Array into a 2D array with conditions

### ISSUE THREAD

**Issue by prerna-rn** [SnowScriptWinterOfCode/LeetCode_Q#221]
You are given an integer array nums. You need to create a 2D array from nums satisfying the following conditions:

    -The 2D array should contain only the elements of the array nums.
    -Each row in the 2D array contains distinct integers.
    -The number of rows in the 2D array should be minimal.

Return the resulting array. If there are multiple answers, return any of them.
Note that the 2D array can have a different number of elements on each row.

Example 1:
Input: nums = [1,3,4,1,2,3,1]
Output: [[1,3,4,2],[1,3],[1]]
Explanation: We can create a 2D array that contains the following rows:
- 1,3,4,2
- 1,3
- 1
All elements of nums were used, and each row of the 2D array contains distinct integers, so it is a valid answer.
It can be shown that we cannot have less than 3 rows in a valid array.

Example 2:
Input: nums = [1,2,3,4]
Output: [[4,3,2,1]]
Explanation: All elements of the array are distinct, so we can keep all of them in the first row of the 2D array.

Constraints:
    1 <= nums.length <= 200
    1 <= nums[i] <= nums.length

Problem link- https://leetcode.com/problems/convert-an-array-into-a-2d-array-with-conditions/

**Comment by shahin-04** [comment]
@prerna-rn Hey, I'd like to contribute. Could you please assign this task to me?

**Comment by namita0210** [comment]
@bh-g I want to solve in java - pls assign this issue to me

**Comment by namita0210** [comment]
> @bh-g I want to solve in java - pls assign this issue to me

pls assign @Nitya-Pasrija
