### ISSUE TITLE
Longest Common Prefix

### ISSUE THREAD

**Issue by Karnankita04** [SnowScriptWinterOfCode/LeetCode_Q#222]
Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "". 

Example 1:

Input: strs = ["flower","flow","flight"]
Output: "fl"

Example 2:

Input: strs = ["dog","racecar","car"]
Output: ""
Explanation: There is no common prefix among the input strings.

Constraints:

1 <= strs.length <= 200
0 <= strs[i].length <= 200
strs[i] consists of only lowercase English letters.

Link: https://leetcode.com/problems/longest-common-prefix/description/

**Comment by Karnankita04** [comment]
@bh-g Please assign this issue to me :)

**Comment by Akansha77** [comment]
Please assign this issue to me @bh-g .

**Comment by Karnankita04** [comment]
please assign this issue to me :)

**Comment by karishma-2020** [comment]
please do not tag maintainers - we are trying our best to assign as soon as possible

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me
