### ISSUE TITLE
Day-7 q1: Asteroid Collision

### ISSUE THREAD

**Issue by SonaVarshney** [SnowScriptWinterOfCode/LeetCode_Q#229]
# Asteroid Collision

We are given an array `asteroids` of integers representing asteroids in a row.

For each asteroid, the absolute value represents its size, and the sign represents its direction (positive meaning right, negative meaning left). Each asteroid moves at the same speed.

Find out the state of the asteroids after all collisions. If two asteroids meet, the smaller one will explode. If both are the same size, both will explode. Two asteroids moving in the same direction will never meet.

 
`Example 1`:

**Input:** asteroids = [5,10,-5]
**Output**: [5,10]
Explanation: The 10 and -5 collide resulting in 10. The 5 and 10 never collide.

`Example 2`:
**Input**: asteroids = [8,-8]
**Output**: []
Explanation: The 8 and -8 collide exploding each other.

`Example 3`:
**Input**: asteroids = [10,2,-5]
**Output**: [10]
Explanation: The 2 and -5 collide resulting in -5. The 10 and -5 collide resulting in 10.
 

`Constraints`:
2 <= asteroids.length <= 104
-1000 <= asteroids[i] <= 1000
asteroids[i] != 0

**Comment by Akansha77** [comment]
Please assign this issue to me.

**Comment by SonaVarshney** [comment]
@bh-g pls merge the PR for the question in the folder - https://github.com/SnowScriptWinterOfCode/LeetCode_Q/pull/286#issue-2066807675 
thanks

**Comment by namita0210** [comment]
@bh-g Pls assign this issue - for a solution in java

**Comment by SonaVarshney** [comment]
@bh-g pls merge the solution for this question. Thanks! https://github.com/SnowScriptWinterOfCode/LeetCode_Q/pull/294#issue-2067216574
