### ISSUE TITLE
Subsets

### ISSUE THREAD

**Issue by Shubhra-Narang** [SnowScriptWinterOfCode/LeetCode_Q#230]
Given an integer array nums of unique elements, return all possible 
subsets
 (the power set).

The solution set must not contain duplicate subsets. Return the solution in any order.

Example 1:

Input: nums = [1,2,3]
Output: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]
Example 2:

Input: nums = [0]
Output: [[],[0]]
 

Constraints:

1 <= nums.length <= 10
-10 <= nums[i] <= 10
All the numbers of nums are unique.

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me!

**Comment by Karnankita04** [comment]
Please assign this issue to me :)
