### ISSUE TITLE
Day 8- Q2: Leaf at same level

### ISSUE THREAD

**Issue by DiyaSingla** [SnowScriptWinterOfCode/LeetCode_Q#260]
Given a Binary Tree, check if all leaves are at same level or not.

Example 1:
```
Input: 
            1
          /   \
         2     3
```
Output: 1

Explanation:  Leaves 2 and 3 are at same level.

Example 2:
```
Input:
            10
          /    \
        20      30
       /  \        
     10    15
```
Output: 0

Explanation:  Leaves 10, 15 and 30 are not at same level.

**Comment by Akansha77** [comment]
Please assign this issue to me.

**Comment by namita0210** [comment]
I want to solve this question in java - pls assign this issue to me @bh-g

**Comment by namita0210** [comment]
> I want to solve this question in java - pls assign this issue to me @bh-g

Pls assign @Nitya-Pasrija
