### ISSUE TITLE
Day 5  Q3- Rotate Image

### ISSUE THREAD

**Issue by Mansi8874** [SnowScriptWinterOfCode/LeetCode_Q#264]
You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image [in-place](https://en.wikipedia.org/wiki/In-place_algorithm), which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

Example 1:
Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [[7,4,1],[8,5,2],[9,6,3]]

Example 2:
Input: matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
Output: [[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]
 
Constraints:
n == matrix.length == matrix[i].length
1 <= n <= 20
-1000 <= matrix[i][j] <= 1000

**Comment by Tech-neophyte** [comment]
Hi! Please assign this question to me. @Mansi8874 @kratika-Jangid @bh-g

**Comment by priyagupta20044** [comment]
Please assign this question to me. @Mansi8874 @kratika-Jangid @bh-g

**Comment by Akansha77** [comment]
Please assign this issue to me.

**Comment by Sakshi2518** [comment]
Please assign this issue to me. I would like to add a solution in java
