### ISSUE TITLE
Day 8 Q3 : Find first non-repeating element in a given Array of integers

### ISSUE THREAD

**Issue by AarnaSinghal** [SnowScriptWinterOfCode/LeetCode_Q#268]
Given an array of integers of size N, the task is to find the first non-repeating element in this array. 

Examples:

Input: {-1, 2, -1, 3, 0}
Output: 2
Explanation: The first number that does not repeat is : 2

Input: {9, 4, 9, 6, 7, 4}
Output: 6

**Comment by aishwarya-chandra** [comment]
please assign this question to me @bh-g @kratika-Jangid

**Comment by vidhiwalia** [comment]
Please assign This issue to me @kratika-Jangid , @bh-g

**Comment by namita0210** [comment]
I want to add a solution in java pls assign this issue to me @bh-g

**Comment by namita0210** [comment]
> I want to add a solution in java pls assign this issue to me @bh-g

pls assign @Nitya-Pasrija

**Comment by aishwarya-chandra** [comment]
A solution in java have already been added @namita0210

**Comment by namita0210** [comment]
> A solution in java have already been added @namita0210

alright - i'll add in python

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by priyagupta20044** [comment]
please assign this question to me @bh-g @kratika-Jangid
