### ISSUE TITLE
Day 9 Q1: Longest Increasing Subsequence

### ISSUE THREAD

**Issue by prachisinhaa** [SnowScriptWinterOfCode/LeetCode_Q#298]
Given an integer array nums, return the length of the longest strictly increasing 
subsequence
.

 

Example 1:
Input: nums = [10,9,2,5,3,7,101,18]
Output: 4
Explanation: The longest increasing subsequence is [2,3,7,101], therefore the length is 4.

Example 2:
Input: nums = [0,1,0,3,2,3]
Output: 4

Example 3:
Input: nums = [7,7,7,7,7,7,7]
Output: 1

**Comment by Tech-neophyte** [comment]
Hey! Please assign this question to me.. @kratika-Jangid @bh-g

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by preetijangra15** [comment]
please assign this issue to me

**Comment by Sakshi2518** [comment]
Hello! Please assign this issue to me
