### ISSUE TITLE
Day 10 Q1: Number of Laser Beams in a Bank

### ISSUE THREAD

**Issue by prerna-rn** [SnowScriptWinterOfCode/LeetCode_Q#303]
Anti-theft security devices are activated inside a bank. You are given a 0-indexed binary string array bank representing the floor plan of the bank, which is an m x n 2D matrix. bank[i] represents the ith row, consisting of '0's and '1's. '0' means the cell is empty, while'1' means the cell has a security device.

There is one laser beam between any two security devices if both conditions are met:

    The two devices are located on two different rows: r1 and r2, where r1 < r2.
    For each row i where r1 < i < r2, there are no security devices in the ith row.

Laser beams are independent, i.e., one beam does not interfere nor join with another.

Return the total number of laser beams in the bank.

Example 1:
![laser1](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/97434896/15db5701-e0a6-44b1-bf2e-411bcb039e7a)
Input: bank = ["011001","000000","010100","001000"]
Output: 8
Explanation: Between each of the following device pairs, there is one beam. In total, there are 8 beams:
 * bank[0][1] -- bank[2][1]
 * bank[0][1] -- bank[2][3]
 * bank[0][2] -- bank[2][1]
 * bank[0][2] -- bank[2][3]
 * bank[0][5] -- bank[2][1]
 * bank[0][5] -- bank[2][3]
 * bank[2][1] -- bank[3][2]
 * bank[2][3] -- bank[3][2]
Note that there is no beam between any device on the 0th row with any on the 3rd row.
This is because the 2nd row contains security devices, which breaks the second condition.

Example 2:

Input: bank = ["000","111","000"]
Output: 0
Explanation: There does not exist two devices located on two different rows.

 
![laser2](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/97434896/779d000a-a77c-48c0-81fb-ddc0f5200ff6)

Constraints:

    m == bank.length
    n == bank[i].length
    1 <= m, n <= 500
    bank[i][j] is either '0' or '1'.

 problem link: https://leetcode.com/problems/number-of-laser-beams-in-a-bank/description/?envType=daily-question&envId=2024-01-03

**Comment by Tech-neophyte** [comment]
Please assign this question to me.. @kratika-Jangid @bh-g

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by namita0210** [comment]
pls assign this ques to me for java soln @bh-g
