### ISSUE TITLE
DAY-11 q1:Find Eventual Safe States

### ISSUE THREAD

**Issue by SonaVarshney** [SnowScriptWinterOfCode/LeetCode_Q#318]
# Find Eventual Safe States

## Problem Description

There is a directed graph of n nodes with each node labeled from 0 to n - 1. The graph is represented by a 0-indexed 2D integer array `graph` where `graph[i]` is an integer array of nodes adjacent to node i, meaning there is an edge from node i to each node in `graph[i]`.
A node is a terminal node if there are no outgoing edges. A node is a safe node if every possible path starting from that node leads to a terminal node (or another safe node).
Return an array containing all the safe nodes of the graph. The answer should be sorted in ascending order.

#### Example 1

`Input` : graph = [[1,2],[2,3],[5],[0],[5],[],[]]  
`Output`: [2,4,5,6]  
`Explanation`: 
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/99477385/b6304257-0b83-465c-beef-023d876f5b10)

Nodes 5 and 6 are terminal nodes as there are no outgoing edges from either of them.
Every path starting at nodes 2, 4, 5, and 6 all lead to either node 5 or 6.

#### Example 2:

`Input`: graph = [[1,2,3,4],[1,2],[3,4],[0,4],[]]  
`Output`: [4]  
`Explanation`:  
Only node 4 is a terminal node, and every path starting at node 4 leads to node 4.

### Constraints:
 • n == graph.length  
 • 1 <= n <= 104  
 • 0 <= graph[i].length <= n  
 • 0 <= graph[i][j] <= n - 1  
 • graph[i] is sorted in a strictly increasing order.  
 • The graph may contain self-loops.  
 • The number of edges in the graph will be in the range [1, 4 * 104].

**Comment by SonaVarshney** [comment]
@karishma-2020 @bh-g pls merge the PR for the question above #317 . Thanks!

**Comment by Tech-neophyte** [comment]
Please assign this question to me. @kratika-Jangid @bh-g @karishma-2020

**Comment by namita0210** [comment]
pls assign this issue to me - for java soln @bh-g

**Comment by SonaVarshney** [comment]
@karishma-2020 @bh-g please merge the solution for this problem. thanks!  https://github.com/SnowScriptWinterOfCode/LeetCode_Q/pull/338#issue-2072215500
