### ISSUE TITLE
Happy numbers

### ISSUE THREAD

**Issue by priyagupta20044** [SnowScriptWinterOfCode/LeetCode_Q#323]
https://leetcode.com/problems/happy-number/description/ 
I want to add the solution to this, please assign this to me @bh-g @kratika-Jangid

**Comment by bh-g** [comment]
Hey Priya, 
Sorry, we're not accepting new questions from contributors anymore!

**Comment by priyagupta20044** [comment]
Hello, apologies for adding a new issue when new questions are not
 accepted, but kindly suggest a way to contribute in this repository. I
 comment and tag the maintainers to assign me the already existing issues
 but they're either not assigned or closed before assigning.
Thank you
@bh-g

**Comment by priyagupta20044** [comment]
@bh-g Please answer, I've commented on existing issues but i haven't been assigned any
