### ISSUE TITLE
Day-10 q3: Merge Two Sorted Linked List

### ISSUE THREAD

**Issue by Smita-Maurya** [SnowScriptWinterOfCode/LeetCode_Q#331]
You are given the heads of two sorted linked lists list1 and list2.

Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.

Return the head of the merged linked list.

Example 1:
Input: list1 = [1,2,4], list2 = [1,3,4]
Output: [1,1,2,3,4,4]

Example 2:
Input: list1 = [], list2 = []
Output: []

**Comment by Pragya1601** [comment]
please assign this issue to me.....

**Comment by Shubh-Krishna** [comment]
please assign this question to me :) @bh-g

**Comment by Akansha77** [comment]
Please assign this issue to me.

**Comment by Smita-Maurya** [comment]
Assigned.

**Comment by namita0210** [comment]
Pls assign to me for java soln @karishma-2020 @bh-g

**Comment by priyagupta20044** [comment]
please assign this question to me @bh-g @kratika-Jangid
