### ISSUE TITLE
longest palindromic substring

### ISSUE THREAD

**Issue by Kalpana8055** [SnowScriptWinterOfCode/LeetCode_Q#341]
Given a string s, return the longest 
palindromic
 
substring
 in s.

 

Example 1:

Input: s = "babad"
Output: "bab"
Explanation: "aba" is also a valid answer.
Example 2:

Input: s = "cbbd"
Output: "bb"

**Comment by Kalpana8055** [comment]
@bh-g this issue assign to me

**Comment by Akansha77** [comment]
Please assign this issue to me.

**Comment by bh-g** [comment]
Hey @Kalpana8055! We're not accepting new questions from contributors. 
You can look at the active issues and find one you want to contribute to :)
