### ISSUE TITLE
Day 14 q3: Implement Stack Using Queues

### ISSUE THREAD

**Issue by Smita-Maurya** [SnowScriptWinterOfCode/LeetCode_Q#343]
Implement a last-in-first-out (LIFO) stack using only two queues. The implemented stack should support all the functions of a normal stack (push, top, pop, and empty).

Implement the MyStack class:
void push(int x) Pushes element x to the top of the stack.
int pop() Removes the element on the top of the stack and returns it.
int top() Returns the element on the top of the stack.
boolean empty() Returns true if the stack is empty, false otherwise.
Notes:

You must use only standard operations of a queue, which means that only push to back, peek/pop from front, size and is empty operations are valid.
Depending on your language, the queue may not be supported natively. You may simulate a queue using a list or deque (double-ended queue) as long as you use only a queue's standard operations.
 

Example 1:
Input
["MyStack", "push", "push", "top", "pop", "empty"]
[[], [1], [2], [], [], []]
Output
[null, null, null, 2, 2, false]

Explanation
MyStack myStack = new MyStack();
myStack.push(1);
myStack.push(2);
myStack.top(); // return 2
myStack.pop(); // return 2
myStack.empty(); // return False

**Comment by namita0210** [comment]
Pls assign this issue to me for java solution @Smita-Maurya

**Comment by Smita-Maurya** [comment]
Assigned to @Namita.

**Comment by Kalpana8055** [comment]
@bh-g please assign me

**Comment by Shubh-Krishna** [comment]
@bh-g please assign this to me :)

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by Smita-Maurya** [comment]
Assigned @Shubh-Krishna

**Comment by priyagupta20044** [comment]
@bh-g please assign this to me

**Comment by Karnankita04** [comment]
@bh-g please assign this issue to me :)
