### ISSUE TITLE
Day 14 q1: Amount of Time for Binary Tree to be Infected

### ISSUE THREAD

**Issue by prerna-rn** [SnowScriptWinterOfCode/LeetCode_Q#350]
Problem link: https://leetcode.com/problems/amount-of-time-for-binary-tree-to-be-infected/description/

You are given the root of a binary tree with unique values, and an integer start. At minute 0, an infection starts from the node with value start.

Each minute, a node becomes infected if:

    The node is currently uninfected.
    The node is adjacent to an infected node.

Return the number of minutes needed for the entire tree to be infected.

Example 1:
![image-20220625231744-1](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/97434896/0639a19c-2c4c-4770-95c2-d5541fd5c0c1)

Input: root = [1,5,3,null,4,10,6,9,2], start = 3
Output: 4
Explanation: The following nodes are infected during:
- Minute 0: Node 3
- Minute 1: Nodes 1, 10 and 6
- Minute 2: Node 5
- Minute 3: Node 4
- Minute 4: Nodes 9 and 2
It takes 4 minutes for the whole tree to be infected so we return 4.

Example 2:

![image-20220625231812-2](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/97434896/cb9fd0b2-a1e9-422f-8b0d-a1c82f825c63)

Input: root = [1], start = 1
Output: 0
Explanation: At minute 0, the only node in the tree is infected so we return 0.

 

Constraints:

    The number of nodes in the tree is in the range [1, 105].
    1 <= Node.val <= 105
    Each node has a unique value.
    A node with a value of start exists in the tree.

**Comment by Kalpana8055** [comment]
@bh-g please this issue assign to me

**Comment by Tech-neophyte** [comment]
@bh-g  Please assign this to me also..

**Comment by Shubh-Krishna** [comment]
please assign this me :) @bh-g

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me
