### ISSUE TITLE
Day-13 q3: Permutation in String

### ISSUE THREAD

**Issue by div910** [SnowScriptWinterOfCode/LeetCode_Q#356]
Given two strings s1 and s2, return true if s2 contains a permutation of s1, or false otherwise.

In other words, return true if one of s1's permutations is the substring of s2.

### Example 1:

Input: s1 = "ab", s2 = "eidbaooo"
Output: true
Explanation: s2 contains one permutation of s1 ("ba").

### Example 2:

Input: s1 = "ab", s2 = "eidboaoo"
Output: false

### Constraints:

1 <= s1.length, s2.length <= 104
s1 and s2 consist of lowercase English letters.

**Comment by Kalpana8055** [comment]
@bh-g please assign this

**Comment by Akansha77** [comment]
Please assign this issue to me.

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by priyagupta20044** [comment]
@bh-g please assign this

**Comment by namita0210** [comment]
Pls assign this issue @bh-g
