### ISSUE TITLE
Day 13 Q2: Longest Palindromic Substring

### ISSUE THREAD

**Issue by Mansi8874** [SnowScriptWinterOfCode/LeetCode_Q#362]
Given a string s, return the longest palindromic substring in s.

Example 1:
Input: s = "babad"
Output: "bab"

Example 2:
Input: s = "cbbd"
Output: "bb"
 

Constraints:
1 <= s.length <= 1000
s consist of only digits and English letters.

**Comment by Bluesparx** [comment]
Pls assign this issue to me

**Comment by Shubh-Krishna** [comment]
please assign this to me :) @bh-g

**Comment by Kalpana8055** [comment]
@bh-g please assign to me

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by Karnankita04** [comment]
please assign this issue to me :)
