### ISSUE TITLE
Day-15 q1: Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by SonaVarshney** [SnowScriptWinterOfCode/LeetCode_Q#364]
# Lowest Common Ancestor of a Binary Tree

## Problem Description

Given a binary tree, find the lowest common ancestor (LCA) of two given nodes in the tree.

According to the definition of LCA on Wikipedia: “The lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants (where we allow a node to be a descendant of itself).”

### Example 1:

`Input`: root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1  
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/99477385/a4422d03-d33f-4a88-b4a3-38b3b2619f6c)  
`Output`: 3  
`Explanation`: The LCA of nodes 5 and 1 is 3.  

### Example 2:

`Input`: root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 4  
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/99477385/78f4633c-cdc8-44e8-aa00-f1b9068df3ef)  
`Output`: 5  
`Explanation`: The LCA of nodes 5 and 4 is 5, since a node can be a descendant of itself according to the LCA definition.  

### Example 3:

`Input`: root = [1,2], p = 1, q = 2  
`Output`: 1  

## Constraints:

- The number of nodes in the tree is in the range [2, 105].  
- -109 <= Node.val <= 109  
- All Node.val are unique.  
- p != q  
- p and q will exist in the tree.

**Comment by SonaVarshney** [comment]
@karishma-2020  @kratika-Jangid @bh-g  pls merge the day-15: q1 to the repo. Thanks :)  #363

**Comment by Shubh-Krishna** [comment]
please assign this question to me :) @bh-g @karishma-2020

**Comment by Akansha77** [comment]
Please assign this issue to me .

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by priyagupta20044** [comment]
please assign this question to me  @bh-g @karishma-2020

**Comment by i-am-SnehaChauhan** [comment]
@bh-g Please assign it to me

**Comment by namita0210** [comment]
Pls assign this issue @bh-g

**Comment by SonaVarshney** [comment]
@kratika-Jangid @karishma-2020 @bh-g please merge the solution ,thanks :) #380
