### ISSUE TITLE
Best Time to buy and sell stock

### ISSUE THREAD

**Issue by MonalikaPatnaik** [SnowScriptWinterOfCode/LeetCode_Q#37]
I want to add this question to this repository along with its solution
![image](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/99353300/888e6b13-4119-4226-8db8-b11f4c206ba0)

**Comment by bh-g** [comment]
Sure, you can add it in LeetCode_Q/ Others, I've assigned it to you.
