### ISSUE TITLE
Day-17 : Q2 - Swap Nodes in Pairs

### ISSUE THREAD

**Issue by Mansi8874** [SnowScriptWinterOfCode/LeetCode_Q#378]
Given a linked list, swap every two adjacent nodes and return its head. You must solve the problem without modifying the values in the list's nodes (i.e., only nodes themselves may be changed.)

Example 1:
Input: head = [1,2,3,4]
Output: [2,1,4,3]

Example 2:
Input: head = []
Output: []

Example 3:
Input: head = [1]
Output: [1]
 
Constraints:
The number of nodes in the list is in the range [0, 100].
0 <= Node.val <= 100

**Comment by Akansha77** [comment]
Please assign this issue to me.

**Comment by priyagupta20044** [comment]
Please assign this issue to me @bh-g

**Comment by namita0210** [comment]
Pls assign this issue to me @karishma-2020
