### ISSUE TITLE
Day-1 q2: Number of Pairs in an Array

### ISSUE THREAD

**Issue by kratika-Jangid** [SnowScriptWinterOfCode/LeetCode_Q#4]
_Number of Pairs in an Array_
Given an array of integers nums and an integer k, return the number of unique k-diff pairs in the array.

A k-diff pair is an integer pair (nums[i], nums[j]), where the following are true:

0 <= i, j < nums.length
i != j
|nums[i] - nums[j]| == k
Notice that |val| denotes the absolute value of val.

 

Example 1:

Input: nums = [3,1,4,1,5], k = 2
Output: 2
Explanation: There are two 2-diff pairs in the array, (1, 3) and (3, 5).
Although we have two 1s in the input, we should only return the number of unique pairs.
Example 2:

Input: nums = [1,2,3,4,5], k = 1
Output: 4
Explanation: There are four 1-diff pairs in the array, (1, 2), (2, 3), (3, 4) and (4, 5).

**Comment by ananyataneja** [comment]
Pls assign this to me

**Comment by Shubh-Krishna** [comment]
please assign it to me....

**Comment by Shubh-Krishna** [comment]
please assign this question to me :)
