### ISSUE TITLE
Count Negative Numbers in a Sorted Matrix

### ISSUE THREAD

**Issue by namita0210** [SnowScriptWinterOfCode/LeetCode_Q#41]
**Problem statement**

Given a m x n matrix grid which is sorted in non-increasing order both row-wise and column-wise, return the number of negative numbers in grid.

[LeetCode Link](https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/?envType=study-plan-v2&envId=binary-search)

**Comment by Karnankita04** [comment]
@karishma-2020  please assign this issue to me.
