### ISSUE TITLE
Day 23 : q2 Staircase Climbing Challenge

### ISSUE THREAD

**Issue by avanimathur** [SnowScriptWinterOfCode/LeetCode_Q#458]
_### _**Staircase Climbing Challenge**__

You are at the bottom of a staircase, and it takes `n` steps to reach the top. Each time, you can choose to climb either 1 or 2 steps. How many unique ways can you reach the top of the staircase?

**Example 1**

Input: n = 2  
Output: 2  
Explanation: There are two distinct ways to climb to the top.
1. Climb 1 step + Climb 1 step
2. Climb 2 steps

**Example 2**

Input: n = 3  
Output: 3  
Explanation: There are three distinct ways to climb to the top.
1. Climb 1 step + Climb 1 step + Climb 1 step
2. Climb 1 step + Climb 2 steps
3. Climb 2 steps + Climb 1 step

**Example 3**

Input: n = 4  
Output: 5  
Explanation: There are five distinct ways to climb to the top.
1. Climb 1 step + Climb 1 step + Climb 1 step + Climb 1 step
2. Climb 1 step + Climb 1 step + Climb 2 steps
3. Climb 1 step + Climb 2 steps + Climb 1 step
4. Climb 2 steps + Climb 1 step + Climb 1 step
5. Climb 2 steps + Climb 2 steps

**Constraints**
1 <= n <= 45

**Comment by avanimathur** [comment]
@kratika-Jangid @karishma-2020 @bh-g 
please merge the question #459

**Comment by Anomasingh** [comment]
Please Assign this issue to me

**Comment by aishwarya-chandra** [comment]
please assign this issue to me.

**Comment by Tech-neophyte** [comment]
Please assign this ques to me @bh-g @karishma-2020

**Comment by bh-g** [comment]
@avanimathur we're not accepting new questions!
