### ISSUE TITLE
Day 24 : q1 Optimal Travel Distance

### ISSUE THREAD

**Issue by avanimathur** [SnowScriptWinterOfCode/LeetCode_Q#462]
### **City Travel Distance**

Imagine you are a professional programmer working on a project to optimize the travel distance between cities. You need to find the **maximum sum of distances you can travel without visiting consecutive cities.**

Given an array '_**distances**_' representing the distances between cities, implement a function that returns the _maximum sum of distances you can travel **without going to consecutive cities.**_

<br>

**Example 1:**

Input: distance = [1,2,3,1]
Output: 4
Explanation: Visit City 1 (distance = 1) and then City 3 (distance = 3).
Total distance you can travel = 1 + 3 = 4.

**Example 2:**

Input: distance = [2,7,9,3,1]
Output: 12
Explanation: Visit City 1 (distance = 2), visit City 3 (distance = 9) and then City 5 (distance = 1).
Total distance you can travel = 2 + 9 + 1 = 12.
 
<br>

**Constraints:**

1 <= distance.length <= 100
0 <= distance[i] <= 400

**Comment by avanimathur** [comment]
@kratika-Jangid @karishma-2020 @bh-g
please assign me to work on this issue

**Comment by aishwarya-chandra** [comment]
please assign this issue to me.

**Comment by i-am-SnehaChauhan** [comment]
@bh-g assign this to me

**Comment by Tech-neophyte** [comment]
@bh-g Please assign this question to me for python code...

**Comment by bh-g** [comment]
@avanimathur not accepting new questions from contributors.
