### ISSUE TITLE
Update Day-4 q3-Network Delay Time

### ISSUE THREAD

**Issue by avanimathur** [SnowScriptWinterOfCode/LeetCode_Q#463]
@bh-g @kratika-Jangid @karishma-2020

Day 4 q3 is unanswered
Please assign me to provide a solution for the same.
Thanks.

**Comment by namita0210** [comment]
Pls assign this issue to me - for java solution @bh-g

**Comment by aishwarya-chandra** [comment]
please assign this issue to me.

**Comment by Anomasingh** [comment]
Please assign this issue to me...

**Comment by Shubh-Krishna** [comment]
please assign this to me :) @bh-g

**Comment by bh-g** [comment]
solution added in #476
