### ISSUE TITLE
Day 21: q2 Integer to Roman

### ISSUE THREAD

**Issue by riya8800** [SnowScriptWinterOfCode/LeetCode_Q#470]
Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.

Symbol       Value
I             1
V             5
X             10
L             50
C             100
D             500
M             1000
For example, 2 is written as II in Roman numeral, just two one's added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.

Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:

I can be placed before V (5) and X (10) to make 4 and 9. 
X can be placed before L (50) and C (100) to make 40 and 90. 
C can be placed before D (500) and M (1000) to make 400 and 900.
Given an integer, convert it to a roman numeral.

 

Example 1:

Input: num = 3
Output: "III"
Explanation: 3 is represented as 3 ones.
Example 2:

Input: num = 58
Output: "LVIII"
Explanation: L = 50, V = 5, III = 3.
Example 3:

Input: num = 1994
Output: "MCMXCIV"
Explanation: M = 1000, CM = 900, XC = 90 and IV = 4.
 

Constraints:

1 <= num <= 3999

**Comment by Tech-neophyte** [comment]
Hey! Plz assign this ques to me @bh-g @karishma-2020

**Comment by Shubh-Krishna** [comment]
please assign this to me :) @bh-g

**Comment by aishwarya-chandra** [comment]
please assign this issue to me

**Comment by priyagupta20044** [comment]
please assign this to me :) @bh-g

**Comment by Anomasingh** [comment]
Please assign this issue to me

**Comment by bh-g** [comment]
Hey @riya8800 this question already exists in the repo, pls add a different question.

@assignees
You can add your solutions here: Day-6/q3-Integer to Roman/
