### ISSUE TITLE
Container With Most Water

### ISSUE THREAD

**Issue by MonalikaPatnaik** [SnowScriptWinterOfCode/LeetCode_Q#48]
Hi, I want to add this question to this repository along with its solution. Kindly assign this to me
[Container With Most Water](https://leetcode.com/problems/container-with-most-water/)

**Comment by shahin-04** [comment]
Hey, I'd like to contribute this question along with its solution to the repository. Could you please assign this task to me?

**Comment by shahin-04** [comment]
Hey, I'd like to contribute this question along with its solution to the repository. Could you please assign this task to me?
[[Container With Most Water](https://leetcode.com/problems/container-with-most-water/)](url)
