### ISSUE TITLE
Day-1 q3: First and last occurrences of x

### ISSUE THREAD

**Issue by kratika-Jangid** [SnowScriptWinterOfCode/LeetCode_Q#5]
Given a sorted array arr containing n elements with possibly some duplicate, the task is to find the first and last occurrences of an element x in the given array.
Note: If the number x is not found in the array then return both the indices as -1.

Example 1:

Input:
n=9, x=5
arr[] = { 1, 3, 5, 5, 5, 5, 67, 123, 125 }
Output:  
2 5
Explanation: 
First occurrence of 5 is at index 2 and last occurrence of 5 is at index 5.

**Comment by aarushisingh2004** [comment]
please assign this to me

**Comment by Karnankita04** [comment]
@bh-g please assign this issue to me

**Comment by bh-g** [comment]
> @bh-g please assign this issue to me

Done, you can start solving now :)

**Comment by Shubh-Krishna** [comment]
Please assign it to me :)
