### ISSUE TITLE
CONCATENATION OF ARRAY 

### ISSUE THREAD

**Issue by Sami-1203** [SnowScriptWinterOfCode/LeetCode_Q#65]
Given an integer array nums of length n, you want to create an array ans of length 2n where ans[i] == nums[i] and ans[i + n] == nums[i] for 0 <= i < n (0-indexed).

Specifically, ans is the concatenation of two nums arrays.

Return the array ans.

**Comment by Shubh-Krishna** [comment]
pls assign this question to me :)

**Comment by Sami-1203** [comment]
@karishma-2020 thankyou!

**Comment by Karnankita04** [comment]
@karishma-2020 please assign this issue to me :)

**Comment by Sami-1203** [comment]
@karishma-2020 is the meet recording uploaded on the website?

**Comment by Karnankita04** [comment]
@bh-g I have solved this issue, would you Please review it , thanks for assigning :)

**Comment by Sami-1203** [comment]
@karishma-2020 I have solved this issue. pls have a look!

**Comment by Sami-1203** [comment]
@karishma-2020 I have solved this issue! #231
