### ISSUE TITLE
1897. Redistribute Characters to Make All Strings Equal

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [SnowScriptWinterOfCode/LeetCode_Q#66]
Hi, I want to add this question to this repository along with its solution. Kindly assign this to me [1897. Redistribute Characters to Make All Strings Equal](https://leetcode.com/problems/redistribute-characters-to-make-all-strings-equal/)

**Comment by namita0210** [comment]
Hey, can you please assign this issue to me - I want to provide a solution for this problem in java.
@bh-g @Nitya-Pasrija
