### ISSUE TITLE
1335. Minimum Difficulty of a Job Schedule

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [SnowScriptWinterOfCode/LeetCode_Q#67]
Hi, I want to add this question to this repository along with its solution. Kindly assign this to me[1335. Minimum Difficulty of a Job Schedule](https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule/)

**Comment by namita0210** [comment]
Hi Please assign this issue to me - I want to solve this problem with java
@Nitya-Pasrija @bh-g
