### ISSUE TITLE
1578. Minimum Time to Make Rope Colorful

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [SnowScriptWinterOfCode/LeetCode_Q#69]
Hi, I want to add this question to this repository along with its solution. Kindly assign this to me @bh-g [1578. Minimum Time to Make Rope Colorful](https://leetcode.com/problems/minimum-time-to-make-rope-colorful/)

**Comment by Shubh-Krishna** [comment]
Please assign this to me :)

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me
