### ISSUE TITLE
53. Maximum Subarray

### ISSUE THREAD

**Issue by aishwarya-chandra** [SnowScriptWinterOfCode/LeetCode_Q#72]
I want to contribute to the repo by adding this question as well as its solution.
Kindly assign me this. @bh-g 
[https://leetcode.com/problems/maximum-subarray/description/](url)

**Comment by aishwarya-chandra** [comment]
kindly assign this to me @kratika-Jangid @bh-g

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by Akansha77** [comment]
Please assign this issue to mee @bh-g @kratika-Jangid

**Comment by priyagupta20044** [comment]
Please assign this issue to mee @bh-g @kratika-Jangid

**Comment by priyagupta20044** [comment]
kindly assign this to me @kratika-Jangid @bh-g
