### ISSUE TITLE
Longest Repeating Character Replacement

### ISSUE THREAD

**Issue by Shanvi2005** [SnowScriptWinterOfCode/LeetCode_Q#78]
You are given a string s and an integer k. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most k times.

Return the length of the longest substring containing the same letter you can get after performing the above operations.

Example 1:

Input: s = "ABAB", k = 2
Output: 4
Explanation: Replace the two 'A's with two 'B's or vice versa.
Example 2:

Input: s = "AABABBA", k = 1
Output: 4
Explanation: Replace the one 'A' in the middle with 'B' and form "AABBBBA".
The substring "BBBB" has the longest repeating letters, which is 4.
There may exists other ways to achieve this answer too.

I would like to include this question in the repository, along with its solution. Please assign me this task. Thank you. @bh-g

**Comment by Shubh-Krishna** [comment]
please assign this to me :)

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me
