### ISSUE TITLE
Day-2 q3: Length Of Last Word 

### ISSUE THREAD

**Issue by Smita-Maurya** [SnowScriptWinterOfCode/LeetCode_Q#8]
Given a string s consisting of words and spaces, return the length of the last word in the string.

A word is a maximal substring consisting of non-space characters only.

Example 1:
Input: s = "Hello World"
Output: 5
Explanation: The last word is "World" with length 5.

Example 2:
Input: s = " fly me to the moon "
Output: 4
Explanation: The last word is "moon" with length 4.

**Comment by aarushisingh2004** [comment]
please assign this to me

**Comment by Gurn-k** [comment]
please assign this issue to me

**Comment by Smita-Maurya** [comment]
Assigned.Please go for it .

**Comment by Smita-Maurya** [comment]
Assigned.Please ho for it.

**Comment by Gurn-k** [comment]
@Smita-Maurya plz help ...Im not able to pull the request ,it is taking a lot of time to commit the changes 
![Screenshot (23)](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/144616456/7db529c7-9714-4f5c-a96a-d41ade7326da)

**Comment by Smita-Maurya** [comment]
Ok, no problem. I will help you.
Taking more time is problem or anything else?

**Comment by Smita-Maurya** [comment]
@Gurn-k first fork the repository and then make PR.

**Comment by Gurn-k** [comment]
@Smita-Maurya i have already forked the repo but it is taking alot of time to commit the changes
it is saying that i can PR only after committing the changes,I will try once again

**Comment by Gurn-k** [comment]
this is my forked repo
![Screenshot (24)](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/144616456/cdfbd907-3917-46e5-8a61-177e5fcfdb4e)
but it is still taking alot of time to commit the changes,without committing im unable to send the pull request :(
![Screenshot (25)](https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/144616456/f12b3276-a911-49e7-add7-e7250a430c4a)
