### ISSUE TITLE
Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by namita0210** [SnowScriptWinterOfCode/LeetCode_Q#80]
Given an array of integers nums sorted in non-decreasing order, find the starting and ending position of a given target value.

If target is not found in the array, return [-1, -1].

You must write an algorithm with O(log n) runtime complexity.

**Comment by mad-alpha** [comment]
@namita0210 Please assign this issue to me.

**Comment by Shubhra-Narang** [comment]
please assign this issue to me

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by priyagupta20044** [comment]
Please assign this issue to me

**Comment by Karnankita04** [comment]
Please assign this issue to me, I would like to do it with a new approach :)
