### ISSUE TITLE
Product Of Array Except Self

### ISSUE THREAD

**Issue by mad-alpha** [SnowScriptWinterOfCode/LeetCode_Q#81]
Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].

Write an algorithm that runs in O(n) time and without using the division operation.

I want to add this question and its solution in the repository. @bh-g Please assign this issue to me.

**Comment by aishwarya-chandra** [comment]
this question is already added. You can check in day1 folder.
