### ISSUE TITLE
540. Single Element in a Sorted Array

### ISSUE THREAD

**Issue by aishwarya-chandra** [SnowScriptWinterOfCode/LeetCode_Q#83]
I want to contribute to the repo by adding this question as well as its solution.
Kindly assign me this. @bh-g 
https://leetcode.com/problems/single-element-in-a-sorted-array/description/

**Comment by ShikhaDhiman1** [comment]
I want to solve the question. Kindly assign me this question

**Comment by bh-g** [comment]
PR merged :)
