### ISSUE TITLE
1480. Running Sum of 1d Array

### ISSUE THREAD

**Issue by aishwarya-chandra** [SnowScriptWinterOfCode/LeetCode_Q#85]
I want to contribute to the repo by adding this question as well as its solution.
Kindly assign me this. @bh-g 
https://leetcode.com/problems/running-sum-of-1d-array/description/

**Comment by Shubh-Krishna** [comment]
please assign this question to me :)

**Comment by aishwarya-chandra** [comment]
sorry,i didn't notice that i wasn't assigned yet.

**Comment by bh-g** [comment]
PR merged:)
