### ISSUE TITLE
1732. Find the Highest Altitude

### ISSUE THREAD

**Issue by aishwarya-chandra** [SnowScriptWinterOfCode/LeetCode_Q#88]
I want to contribute to the repo by adding this question as well as its solution.
Kindly assign me this. @bh-g 
https://leetcode.com/problems/find-the-highest-altitude/description/

**Comment by Karnankita04** [comment]
@bh-g  please assign this is issue to me :)

**Comment by Shubh-Krishna** [comment]
Please assign this to me :)

**Comment by bh-g** [comment]
PP merged:)
