### ISSUE TITLE
Sliding Windows

### ISSUE THREAD

**Issue by Karnankita04** [SnowScriptWinterOfCode/LeetCode_Q#89]
**Longest Substring Without Repeating Characters**
Given a string s, find the length of the longest 
substring
 without repeating characters.

 

Example 1:

Input: s = "abcabcbb"
Output: 3
Explanation: The answer is "abc", with the length of 3.
Example 2:

Input: s = "bbbbb"
Output: 1
Explanation: The answer is "b", with the length of 1.

Example 3:

Input: s = "pwwkew"
Output: 3
Explanation: The answer is "wke", with the length of 3.
Notice that the answer must be a substring, "pwke" is a subsequence and not a substring.
 
Link : https://leetcode.com/problems/longest-substring-without-repeating-characters/description/

**Comment by Karnankita04** [comment]
@bh-g @karishma-2020  please assign this issue to me, I am really interested :)

**Comment by Shubh-Krishna** [comment]
please assign this to me :)

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me
