### ISSUE TITLE
4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by aarushisingh2004** [SnowScriptWinterOfCode/LeetCode_Q#96]
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

The overall run time complexity should be O(log (m+n)).

 

Example 1:

Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000
Explanation: merged array = [1,2,3] and median is 2.
Example 2:

Input: nums1 = [1,2], nums2 = [3,4]
Output: 2.50000
Explanation: merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.
 

Constraints:

nums1.length == m
nums2.length == n
0 <= m <= 1000
0 <= n <= 1000
1 <= m + n <= 2000
-106 <= nums1[i], nums2[i] <= 106

**Comment by aarushisingh2004** [comment]
please assign this question to me

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me

**Comment by namita0210** [comment]
@bh-g Please assign this issue to me - for a java solution

**Comment by Akansha77** [comment]
Please assign this issue to me.

**Comment by Karnankita04** [comment]
Please assign this issue to me :)
