### ISSUE TITLE
242. Valid Anagram

### ISSUE THREAD

**Issue by aarushisingh2004** [SnowScriptWinterOfCode/LeetCode_Q#97]
Given two strings s and t, return true if t is an anagram of s, and false otherwise.

An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.

 

Example 1:

Input: s = "anagram", t = "nagaram"
Output: true
Example 2:

Input: s = "rat", t = "car"
Output: false
 

Constraints:

1 <= s.length, t.length <= 5 * 104
s and t consist of lowercase English letters.

**Comment by aarushisingh2004** [comment]
please assign this question to me

**Comment by Karnankita04** [comment]
please assign this issue to me :)

**Comment by Shubh-Krishna** [comment]
please assign this to me :)
